### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by ghost** [miguelmota/metamask-vault-decrypter#1]
admin@admin MINGW64 /c/test/UTILS/others/metamask-vault-decrypter-master
$ metamask-vault-decrypter vault.js -password mysecretpassword
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '../index.js'
Require stack:
- C:\test\UTILS\others\metamask-vault-decrypter-master\metamask-vault-decrypter
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\test\UTILS\others\metamask-vault-decrypter-master\metamask-vault-decrypter:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\test\\UTILS\\others\\metamask-vault-decrypter-master\\metamask-vault-decrypter'
  ]
}

**Comment by ghost** [comment]
also

```
$ metamask-vault-decrypter vault.js -password mysecretpassword
C:\test\UTILS\others\metamask-vault-decrypter-master\node_modules\node-passworder\index.js:5
  crypto.getRandomValues = require('get-random-values')
                         ^

TypeError: Cannot set property 'getRandomValues' of undefined
    at Object.<anonymous> (C:\test\UTILS\others\metamask-vault-decrypter-master\node_modules\node-passworder\index.js:5:26)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\test\UTILS\others\metamask-vault-decrypter-master\index.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
```

**Comment by miguelmota** [comment]
@kipilk0 what's your node version? I believe it only works with node v15 and above since this utility is a wrapper over another browser based metamask library that uses native crypto libraries which aren't available in older versions of node.

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/metamask-vault-decrypter/commit/38c73ee3e5c9a881ab7c084c1ff606c1b8457688
